# Generated by Django 4.2.5 on 2023-10-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField(help_text='A blog post paragraph.')),
                ('description', models.TextField(blank=True, help_text='A detailed description of the project.')),
                ('intended_location', models.TextField(blank=True, help_text='The intended location to write the snippet to.')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpostparagraph')),
            ],
        ),
    ]
