# Generated by Django 4.2.6 on 2023-12-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
