# Generated by Django 4.2.5 on 2023-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='URL to live project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(default=' ', help_text='URL to remote git repo.'),
            preserve_default=False,
        ),
    ]
