# Generated by Django 4.2.5 on 2023-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('gh', 'GitHub'), ('in', 'LinkedIn'), ('fb', 'Facebook'), ('ig', 'Instagram'), ('yt', 'YouTube')], max_length=2, unique=True)),
                ('url', models.URLField(help_text='URL to social media page.', unique=True)),
            ],
        ),
    ]
